apiVersion: v1
kind: Secret
metadata:
  name: minecraft.players
  namespace: global-secrets
data:
  # WHITELIST: 
  OPS: YnJpbWRvcg==
type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  name: minecraft.rcon
  namespace: global-secrets
data:
  RCON_PASSWORD: b2MuZVV6ZWdoeno2NzM0Z1YhVDRudkgyIWZSRjl0VXU=
type: Opaque